### ISSUE TITLE
运行项目，找不到文件CoreNLP-chinese.properties

### ISSUE THREAD

**Issue by xiaojidonggong** [jiekechoo/NLPStudy#3]
通过maven下载完依赖的jar，直接运行项目提示

SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Exception in thread "main" edu.stanford.nlp.io.RuntimeIOException: ERROR: cannot find properties file "CoreNLP-chinese.properties" in the classpath!
	at edu.stanford.nlp.pipeline.StanfordCoreNLP.<init>(StanfordCoreNLP.java:153)
	at edu.stanford.nlp.pipeline.StanfordCoreNLP.<init>(StanfordCoreNLP.java:147)
	at com.sectong.NLPStudy.CoreNLPSegment.main(CoreNLPSegment.java:19)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)

**Comment by jiekechoo** [comment]
请看README.md说明
**准备工作
需要下载 CoreNLP 和 中文处理模型Chinese Model**

**Comment by xiaojidonggong** [comment]
@jiekechoo 我是通过maven去直接下载的，也看了m2目录下有对应的jar
~/.m2/repository/edu/stanford/nlp/stanford-corenlp/3.6.0 » ls
_maven.repositories
stanford-corenlp-3.6.0-models-chinese.jar
stanford-corenlp-3.6.0-models.jar
stanford-corenlp-3.6.0.jar
stanford-corenlp-3.6.0.pom

依旧报告这个错误.

不过错误的原因找到了。是因为配置文件 CoreNLP-chinese.properties 没有被IDEA所找到。 解决方法

1.在项目路径  src/main/java  下创建文件  resource 
2. 把 CoreNLP-chinese.properties 放置进去
3.选中resource文件夹，鼠标右键点击，展开栏中选择 Mark Directory As ->  Resource Root 此时 resource文件夹被标记成resource文件夹
重新运行，成功。
